== API Reference

Here you can find a full reference of the functions provided by the NileRuntimeEnvironment.

[.contract-index]
.Functions
--
* xref:#compile[`++compile++`]
* xref:#deploy[`++deploy++`]
* xref:#call[`++call++`]
* xref:#get_deployment[`++get_deployment++`]
* xref:#get_declaration[`++get_declaration++`]
* xref:#get_or_deploy_account[`++get_or_deploy_account++`]
* xref:#get_accounts[`++get_accounts++`]
* xref:#get_nonce[`++get_nonce++`]
* xref:#get_balance[`++get_balance++`]

--


[.contract-item]
[[compile]]
==== `[.contract-item-name]#++compile++#++(contracts, cairo_path=None) → None++`

Compile a list of contracts.

===== Arguments

- _contracts_
+
List of contracts to compile.
- _cairo_path_
+
Specify a set of directory for the cairo compiler to resolve imports.

[.contract-item]
[[deploy]]
==== `[.contract-item-name]#++deploy++#++(contract, arguments=None, alias=None, overriding_path=None, abi=None, mainnet_token=None, watch_mode=None) → (address, abi)++`

Deploy a smart contract (Deprecated in favor of deployments through accounts).

===== Arguments

- _contract_
+
Contract to deploy.
- _arguments_
+
List of argument for the constructor (calldata).
- _alias_
+
Alias for deployment registration.
- _overriding_path_
+
Override for the path to artifacts and abis.
- _abi_
+
Use a different abi for registration (useful for proxies).
- _mainnet_token_
+
Token for mainnets deployments.
- _watch_mode_
+
Either `track` or `debug` (check `status` command).

===== Return values

- _address_
+
The address of the new contract.
- _abi_
+
The abi registered in deployments.

[.contract-item]
[[call]]
==== `[.contract-item-name]#++call++#++(address_or_alias, method, params=None, abi=None) → output++`

Call a view function in a smart contract.

===== Arguments

- _address_or_alias_
+
Identifier for the contract to call (alias needs to be registered in deployments).
- _method_
+
Method to call.
- _params_
+
Arguments for the call.
- _abi_
+
Override for the abi if necessary.

===== Return values

- _output_
+
The output from the underlaying starknet cli call.