:starknet-devnet: link:https://github.com/Shard-Labs/starknet-devnet/[starknet-devnet]
:cairo-lang: link:https://github.com/starkware-libs/cairo-lang[cairo-lang]
:imports: link:https://starknet.io/docs/how_cairo_works/imports.html?highlight=cairo%20path#import-search-paths[Import search paths]
:status: link:#status[status]
:devnet-doc: link:https://shard-labs.github.io/starknet-devnet/docs/guide/run[starknet-devnet documentation]

= CLI Reference

Here you can find a complete reference of the core commands Nile provides by default.

== Transaction execution

Commands for executing or querying the status of a transaction.

=== `setup`

[.contract-item]
[[setup]]
==== `[.contract-item-name]#++nile setup <PRIVATE_KEY_ALIAS>++#`

Deploy an Account associated with a given private key.

IMPORTANT: This command takes an alias instead of the actual private key to avoid accidentally leaking private keys. This alias is associated with an environmental variable of the same name, whose value is the private key.

[NOTE]
====
. Creates or updates `localhost.accounts.json` file storing all data related to accounts management.
. Creates or updates `localhost.deployments.txt` file storing all data related to deployments.
====

===== Arguments

- `*PRIVATE_KEY_ALIAS*`
+
Specify the private key that will own the account to be deployed. Looks for an environment variable with the name of the private key alias.

===== Options

include::snippets.adoc[tag=network-options]
+
include::snippets.adoc[tag=salt]
+
include::snippets.adoc[tag=max-fee]
+
include::snippets.adoc[tag=query-options]
+
include::snippets.adoc[tag=status-options]

=== `declare`

[.contract-item]
[[declare]]
==== `[.contract-item-name]#++nile declare  <PRIVATE_KEY_ALIAS> <CONTRACT_NAME>++#`

Declare a contract through an Account.

===== Arguments

- `*PRIVATE_KEY_ALIAS*`
+
Specify the alias representing the account to be used.
- `*CONTRACT_NAME*`
+
Specify the name of the contract artifact to be declared.

===== Options

include::snippets.adoc[tag=network-options]
+
include::snippets.adoc[tag=max-fee]
+
- `*--alias*`
+
The alias for registering the declared class_hash (DEPRECATED).
+
- `*--overriding_path*`
+
Override the directory path for artifacts discovery.
+
include::snippets.adoc[tag=query-options]
+
include::snippets.adoc[tag=status-options]

=== `deploy`

[.contract-item]
[[deploy]]
==== `[.contract-item-name]#++nile deploy <PRIVATE_KEY_ALIAS> <CONTRACT> [arg1, arg2...]++#`

Deploy a contract through an Account.

[NOTE]
====
. Creates or updates `localhost.deployments.txt` file storing all data related to deployments.
====

===== Arguments

- `*PRIVATE_KEY_ALIAS*`
+
Specify the alias representing the account to be used.
- `*CONTRACT*`
+
Specify the name of the contract artifact to be deployed.
- `*ARGS*`
+
Optional calldata arguments for the constructor.

===== Options

include::snippets.adoc[tag=network-options]
+
include::snippets.adoc[tag=salt]
+
include::snippets.adoc[tag=max-fee]
+
- `*--alias*`
+
Specify the alias for Nile local registration purposes. This allows you to interact with
the contract later without using the address directly.
+
- `*--unique*`
+
Specify that the account address should be taken into account for target address generation.
- `*--abi*`
+
Override artifact abi to be registered. Useful for proxies.
- `*--deployer_address*`
+
Specify the deployer contract if needed.
+
include::snippets.adoc[tag=query-options]
+
include::snippets.adoc[tag=status-options]

=== `send`

[.contract-item]
[[send]]
==== `[.contract-item-name]#++nile send <PRIVATE_KEY_ALIAS> <CONTRACT_ID> <METHOD> [arg1, arg2...]++#`

Execute a transaction through an Account.

===== Arguments

- `*PRIVATE_KEY_ALIAS*`
+
Specify the alias representing the account to be used.
- `*CONTRACT_ID*`
+
Specify the contract to call (either alias or address).
- `*METHOD*`
+
Specify the method to execute.
- `*ARGS*`
+
Optional calldata arguments for the method to execute.

===== Options

include::snippets.adoc[tag=network-options]
+
include::snippets.adoc[tag=max-fee]
+
include::snippets.adoc[tag=query-options]
+
include::snippets.adoc[tag=status-options]

=== `status`

[.contract-item]
[[status]]
==== `[.contract-item-name]#++nile status <TX_HASH>++#`

Query the current status of a transaction.

===== Arguments

- `*TX_HASH*`
+
Specify the hash of the transaction to query.

===== Options

include::snippets.adoc[tag=network-options]
+
- `*--track*`
+
Continue probing the network in case of pending transaction states.
- `*--debug*`
+
Use locally available contracts to make error messages from rejected transactions more explicit.
+
Implies `--track`.
- `*--contracts_file*`
+
Override the deployments file to query the contract artifacts from.
+
Default to `<NETWORK>.deployments.txt`.

[.contract-item]
[[debug]]
==== `[.contract-item-name]#++nile debug <TX_HASH>++#`

Alias for `nile status --debug`.

== Queries

Utilities for querying the blockchain.

=== `call`

[.contract-item]
[[call]]
==== `[.contract-item-name]#++nile call <CONTRACT_ID> <METHOD> [arg1, arg2...]++#`

Perform reading operations against a network.

===== Arguments

- `*CONTRACT_ID*`
+
Specify the contract to call (either alias or address).
- `*METHOD*`
+
Specify the method to call.
- `*ARGS*`
+
Optional calldata arguments for the method to query.

===== Options

include::snippets.adoc[tag=network-options]

=== `get-nonce`

[.contract-item]
[[get-nonce]]
==== `[.contract-item-name]#++nile get-nonce <ADDRESS>++#`

Retrieve the nonce for a contract (usually an account).

===== Arguments

- `*ADDRESS*`
+
Specify the address of the contract to query.

===== Options

include::snippets.adoc[tag=network-options]

=== `get-balance`

[.contract-item]
[[get-balance]]
==== `[.contract-item-name]#++nile get-balance <ADDRESS>++#`

Retrieve the Ether balance for a contract.

===== Arguments

- `*ADDRESS*`
+
Specify the address of the contract to query.

===== Options

include::snippets.adoc[tag=network-options]

== Project management

Utilities for managing the project.

=== `init`

[.contract-item]
[[init]]
==== `[.contract-item-name]#++nile init++#`

Scaffold a simple Nile project.

=== `node`

[.contract-item]
[[node]]
==== `[.contract-item-name]#++nile node++#`

Run a local {starknet-devnet} node.

NOTE: Accepts all the options that the starknet-devnet node accepts by default. Check the {devnet-doc} for a full
list of them.

===== Options

- `*--host*`
+
Specify the address to listen at.
+
Defaults to 127.0.0.1 (use the address the program outputs on start).
- `*--port*`
+
Specify the port to listen at. Defaults to 5050.

===== Starknet Devnet Options

- _This command exposes all the functionalities provided within the starknet-devnet node, like forking mainnet, or specifying the contract class to be used for predeployed accounts. Check the {devnet-doc} for a full description of the arguments._

=== `compile`

[.contract-item]
[[compile]]
==== `[.contract-item-name]#++nile compile [PATH_TO_CONTRACT]++#`

Compile Cairo contracts.

Compilation artifacts are written into the `artifacts/` directory.

===== Arguments

- `*PATH_TO_CONTRACT*`
+
Specify the path to a contract for compiling.

===== Options

- `*--directory*`
+
Specify a directory to compile contracts from.
- `*--account_contract*`
+
As of {cairo-lang} v0.8.0, users must compile account contracts with the `--account_contract` flag. Nile automatically inserts the flag if the contract's name ends with Account. i.e. `Account.cairo`, `EthAccount.cairo`. Otherwise, the flag must be included by the user.
+
[,sh]
----
nile compile contracts/NewAccountType.cairo --account_contract # compiles account contract
----
- `*--cairo_path*`
+
Specify which directories the compiler must use to resolve imports from Cairo.
+
TIP: Check {imports} from StarkNet documentation.
- `*--disable-hint-validation*`
+
Compile allowing unwhitelisted hints.

=== `run`

[.contract-item]
[[run]]
==== `[.contract-item-name]#++nile run <PATH_TO_SCRIPT>++#`

Execute a script in the context of NRE.

===== Arguments

- `*PATH_TO_SCRIPT*`
+
Path to the script to run.

===== Options

include::snippets.adoc[tag=network-options]

=== `clean`

[.contract-item]
[[clean]]
==== `[.contract-item-name]#++nile clean++#`

Deletes the `artifacts/` folder and deployments files.

=== `version`

[.contract-item]
[[version]]
==== `[.contract-item-name]#++nile version++#`

Print out the Nile version.

== Utils

Other utilities.

=== `get-accounts`

[.contract-item]
[[get-accounts]]
==== `[.contract-item-name]#++nile get-accounts++#`

Retrieve a list of ready-to-use accounts which allows for easy scripting integration.

[NOTE]
====
The list of accounts includes only those that exist in the local `<NETWORK>.accounts.json` file. In a recent release we added a flag to the command, to get predeployed accounts if the network you are connected to is a starknet-devnet instance.

Sending transactions through predeployed accounts can be done through scripting, but the current CLI version doesn't allow using these accounts for `nile send`.
====

===== Options

include::snippets.adoc[tag=network-options]
+
- `*--predeployed*`
+
Query a devnet node for predeployed accounts.

=== `counterfactual-address`

[.contract-item]
[[counterfactual-address]]
==== `[.contract-item-name]#++nile counterfactual-address <PRIVATE_KEY_ALIAS>++#`

Precompute the deployment address of an Account contract.

===== Arguments

- `*PRIVATE_KEY_ALIAS*`
+
Specify the alias representing the private key to be used.

===== Options

include::snippets.adoc[tag=salt]
+
Default to 0.
