:starknet-devnet: link:https://github.com/Shard-Labs/starknet-devnet/[starknet-devnet]
:cairo-lang: link:https://github.com/starkware-libs/cairo-lang[cairo-lang]
:imports: link:https://starknet.io/docs/how_cairo_works/imports.html?highlight=cairo%20path#import-search-paths[Import search paths]
:status: link:#status[status]

= CLI Reference

Here you can find a full reference of the core commands Nile provides by default.

== node

Run a local {starknet-devnet} node:

[,sh]
----
nile node [--host HOST] [--port PORT] [--seed SEED] [--lite_mode]
----

=== Options

==== *--host*

Specify the address to listen at. Defaults to 127.0.0.1 (use the address the program outputs on start).

==== *--port*

Specify the port to listen at. Defaults to 5050.

==== *--seed*

Specify the seed for randomness of accounts to be deployed.

==== *--lite-mode*

Applies all lite-mode optimizations by disabling features such as block hash and deploy hash calculation.

== compile

Compile Cairo contracts.

Compilation artifacts are written into the *artifacts/* directory.

[,sh]
----
nile compile [PATH_TO_CONTRACT] ...
----

=== Arguments

==== *PATH_TO_CONTRACT*

Specify the path to a contract for compiling.

=== Options

==== *--directory*

Specify a directory to compile contracts from.

==== *--account_contract*

As of {cairo-lang} v0.8.0, account contracts must be compiled with the `--account_contract` flag. Nile automatically inserts the flag if the contract's name ends with Account. i.e. *Account.cairo*, *EthAccount.cairo*. Otherwise, the flag must be included by the user.

[,sh]
----
nile compile contracts/NewAccountType.cairo --account_contract # compiles account contract
----

==== *--cairo_path*

Specify which directories the compiler must use to resolve imports from Cairo. 

TIP: Check {imports} from StarkNet documentation.

==== *--disable-hint-validation*

Compile allowing unwhitelisted hints.


== setup

Deploy an Account associated with a given private key.

To avoid accidentally leaking private keys, this command takes an alias instead of the actual private key. This alias is associated with an environmental variable of the same name, whose value is the actual private key.

[,sh]
----
nile setup <PRIVATE_KEY_ALIAS>
----

[NOTE]
====
- This creates or updates *localhost.accounts.json* file storing all data related to accounts management.
- This creates or updates *localhost.deployments.txt* file storing all data related to deployments.
====

=== Arguments

==== *PRIVATE_KEY_ALIAS*

Specify the private key that will own the account to be deployed. Looks for an environment variable with the name of the private key alias.

=== Options

==== *--network*

Select network, one of ('localhost', 'integration', 'goerli', 'goerli2', 'mainnet'). Default to localhost.

==== *--debug* and *--track*

Watch the status of the account deployment transaction. See the {status} command for a complete description.

== declare

Declare a contract through an Account.

[,sh]
----
nile declare <PRIVATE_KEY_ALIAS> <CONTRACT_NAME> [--network NETWORK]
----

[NOTE]
====
- This creates or updates *localhost.accounts.json* file storing all data related to accounts management.
- This creates or updates *localhost.deployments.txt* file storing all data related to deployments.
====

=== Arguments

==== *PRIVATE_KEY_ALIAS*

Specify the alias representing the account to be used.

==== *CONTRACT_NAME*

Specify the name of the contract artifact to be deployed.

=== Options

==== *--network*

Select network, one of ('localhost', 'integration', 'goerli', 'goerli2', 'mainnet'). Default to localhost.

==== *--max_fee*

Specify the max fee you are willing to pay for the transaction.

==== *--overriding_path*

Override the directory path for artifacts discovery.

==== *--token*

Used for deploying contracts to Alpha Mainnet.

==== *--debug* and *--track*

Watch the status of the account deployment transaction. See the {status} command for a complete description.
