:starknet-devnet: link:https://github.com/Shard-Labs/starknet-devnet/[starknet-devnet]
:cairo-lang: link:https://github.com/starkware-libs/cairo-lang[cairo-lang]
:imports: link:https://starknet.io/docs/how_cairo_works/imports.html?highlight=cairo%20path#import-search-paths[Import search paths]
:status: link:#status[status]

== CLI Reference

Here you can find a full reference of the core commands Nile provides by default.

[.contract-index]
.Core Commands
--
* xref:#node[`++node++`]
* xref:#compile[`++compile++`]
* xref:#setup[`++setup++`]
* xref:#declare[`++declare++`]
* xref:#deploy[`++deploy++`]
* xref:#call[`++call++`]
* xref:#send[`++send++`]
* xref:#counterfactual-address[`++counterfactual-address++`]
* xref:#status[`++status++`]
* xref:#debug[`++debug++`]
* xref:#get-accounts[`++get-accounts++`]
* xref:#get-nonce[`++get-nonce++`]
* xref:#get-balance[`++get-balance++`]
* xref:#run[`++run++`]
* xref:#clean[`++clean++`]
* xref:#init[`++init++`]
* xref:#version[`++version++`]
--

[.contract-item]
[[node]]
==== `[.contract-item-name]#++nile node++#`

Run a local {starknet-devnet} node.

===== Options

- _--host_
+
Specify the address to listen at. 
+
Defaults to 127.0.0.1 (use the address the program outputs on start).
- _--port_
+
Specify the port to listen at. Defaults to 5050.
- _--seed_
+
Specify the seed for randomness of accounts to be deployed.
- _--lite-mode_
+
Applies all lite-mode optimizations by disabling features such as block hash and deploy hash calculation.

[.contract-item]
[[compile]]
==== `[.contract-item-name]#++nile compile [PATH_TO_CONTRACT]++#`

Compile Cairo contracts.

Compilation artifacts are written into the *artifacts/* directory.

===== Arguments

- _PATH_TO_CONTRACT_
+
Specify the path to a contract for compiling.

===== Options

- _--directory_
+
Specify a directory to compile contracts from.
- _--account_contract_
+
As of {cairo-lang} v0.8.0, account contracts must be compiled with the `--account_contract` flag. Nile automatically inserts the flag if the contract's name ends with Account. i.e. *Account.cairo*, *EthAccount.cairo*. Otherwise, the flag must be included by the user.
+
[,sh]
----
nile compile contracts/NewAccountType.cairo --account_contract # compiles account contract
----
- _--cairo_path_
+
Specify which directories the compiler must use to resolve imports from Cairo.
+
TIP: Check {imports} from StarkNet documentation.
- _--disable-hint-validation_
+
Compile allowing unwhitelisted hints.

[.contract-item]
[[setup]]
==== `[.contract-item-name]#++nile setup <PRIVATE_KEY_ALIAS>++#`

Deploy an Account associated with a given private key.

IMPORTANT: To avoid accidentally leaking private keys, this command takes an alias instead of the actual private key. This alias is associated with an environmental variable of the same name, whose value is the actual private key.

[NOTE]
====
- This creates or updates *localhost.accounts.json* file storing all data related to accounts management.
- This creates or updates *localhost.deployments.txt* file storing all data related to deployments.
====

===== Arguments

- _PRIVATE_KEY_ALIAS_
+
Specify the private key that will own the account to be deployed. Looks for an environment variable with the name of the private key alias.

===== Options

- _--network_
+
Select network: one of ('localhost', 'integration', 'goerli', 'goerli2', 'mainnet'). 
+
Default to localhost.
- _--debug_ and _--track_
+
Watch the status of the account deployment transaction. See the {status} command for a complete description.

[.contract-item]
[[declare]]
==== `[.contract-item-name]#++nile declare  <PRIVATE_KEY_ALIAS> <CONTRACT_NAME>++#`

Declare a contract through an Account.

[NOTE]
====
- This creates or updates *localhost.accounts.json* file storing all data related to accounts management.
- This creates or updates *localhost.deployments.txt* file storing all data related to deployments.
====

===== Arguments

- _PRIVATE_KEY_ALIAS_
+
Specify the alias representing the account to be used.
- _CONTRACT_NAME_
+
Specify the name of the contract artifact to be deployed.

===== Options

- _--network_
+
Select network: one of ('localhost', 'integration', 'goerli', 'goerli2', 'mainnet').
+
Default to localhost.
- _--max_fee_
+
Specify the max fee you are willing to pay for the transaction.
- _--overriding_path_
+
Override the directory path for artifacts discovery.
- _--token_
+
Used for deploying contracts to Alpha Mainnet.
- _--debug_ and _--track_
+
Watch the status of the account deployment transaction. See the {status} command for a complete description.

[.contract-item]
[[deploy]]
==== `[.contract-item-name]#++nile deploy++#`

[.contract-item]
[[call]]
==== `[.contract-item-name]#++nile call++#`

[.contract-item]
[[send]]
==== `[.contract-item-name]#++nile send++#`

[.contract-item]
[[counterfactual-address]]
==== `[.contract-item-name]#++nile counterfactual-address++#`

[.contract-item]
[[status]]
==== `[.contract-item-name]#++nile status++#`

[.contract-item]
[[debug]]
==== `[.contract-item-name]#++nile debug++#`

[.contract-item]
[[get-accounts]]
==== `[.contract-item-name]#++nile get-accounts++#`

[.contract-item]
[[get-nonce]]
==== `[.contract-item-name]#++nile get-nonce++#`

[.contract-item]
[[get-balance]]
==== `[.contract-item-name]#++nile get-balance++#`

[.contract-item]
[[run]]
==== `[.contract-item-name]#++nile run++#`

[.contract-item]
[[clean]]
==== `[.contract-item-name]#++nile clean++#`

[.contract-item]
[[init]]
==== `[.contract-item-name]#++nile init++#`

[.contract-item]
[[version]]
==== `[.contract-item-name]#++nile version++#`
