:pyenv: link:https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.4.0b/src/openzeppelin/access/ownable/library.cairo[pyenv]

= Overview

Nile is a CLI tool to develop or interact with Starknet projects written in Cairo. It consists of different components for developing, compiling, testing, and deploying your smart contracts and dApps, providing a CLI for executing tasks, and a Runtime Environment (NRE) for scripting.

The package is designed to be extensible and very customizable by using plugins. This guide will take you through the installation of our recommended setup, but as we expect a lot of functionality coming from plugins, you are free to customize it.

TIP: You can get a list of plugins extending Nile functionality from the xref:plugins.adoc[Plugins] section.

== Requirements

=== Supported Python versions

Some Nile dependencies have specific python version requirements, therefore we recommend using a python version manager like {pyenv}, and virtual environments to avoid conflicts.

IMPORTANT: Current supported Python versions are >=3.8 and <3.10.

