:oz-account: link:https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/presets/Account.cairo[Openzeppelin Account]

= Quick Start

We will explore the basics of creating a Nile project with a sample contract, test it locally, deploy an account and the contract to a devnet node, and send transactions through the account to the contract.

== Installation

Create a folder for your project and cd into it:

[,sh]
----
mkdir myproject && cd myproject
----

Create a virtualenv and activate it:

[,sh]
----
python3 -m venv env
source env/bin/activate
----

NOTE: Review xref:index.adoc#requirements[Requirements]

Install Nile:

[,sh]
----
(env): pip install cairo-nile
----

Use `nile init` to quickly set up your development environment:

[,sh]
----
(env): nile init
🗄 Creating project directory tree
⛵️ Nile project ready! Try running:

nile compile
----

== Testing

`nile init` creates a sample Cairo contract and tests for you. Check *contracts/contract.cairo* and *tests/test_contract.py* for the source code.

Run `pytest` to run the test suite against the Smart Contracts:

[,sh]
----
(env): pytest tests/
----

TIP: For a more in deep guide on testing with parallelism and coverage, check our xref:testing.adoc[Testing] guide.

== Compiling

Use `nile compile` to compile contracts under the *contracts/* folder by default.

[,sh]
----
(env): nile compile
🤖 Compiling all Cairo contracts in the contracts directory
🔨 Compiling contracts/contract.cairo
✅ Done
----

TIP: For a full reference of nile command options, check the xref:commands.adoc[CLI Refenrece] section.

== Deploying an account

. Add an environment variable with the Account Private Key to the *.env* file.
+
[,sh]
----
# .env
ACCOUNT_1 = 0x1234
----
+
CAUTION: Don't use this Private Key in production environments!
+
. Use `nile counterfactual-address` to precompute the deployment address of the Account contract, for the given signer.
+
[,sh]
----
(env): nile counterfactual-address ACCOUNT_1 --salt 123
0x00193c9bf3f66f556b40f0e95dffdd07db2cd6b10552a75048b71550049d1246
----
+
NOTE: Keep in mind that different salts compute to different addresses, even with the same Private Key.
+
. In production, you will need to fund this address with Ether to pay for the deployment fees. In testnets will be mandatory soon. There are multiple bridges and faucets like link:https://goerli.starkgate.starknet.io/[Starkgate] being implemented at the moment to support the developer experience.
+
. After funding the precomputed address, deploy the account using `nile setup`.
+
[,sh]
----
(env): nile setup ACCOUNT_1 --salt 123
----
+
[IMPORTANT]
====
In StarkNet, only contracts that have been previously declared, can be deployed. {oz-account} is declared soon after every release in testnets and mainnet, but local devnet needs a declaration for every instance, because the contract is not declared by default. For declaring you need an account, so to solve this egg-chicken problem, you need to declare OZ Account in devnet using predeployed accounts through scripts.

Check xref:declare_account.adoc[Declare OZ Account in Devnet] guide.
====

== Deploying a contract

. First, declare the contract to register the class hash on the network. You only need to do this once as long as the contract bytecode doesn't change.
+
[,sh]
----
(env): nile declare ACCOUNT_1 contract
----
+
. Use `nile deploy` to deploy the contract.
+
[,sh]
----
(env): nile deploy ACCOUNT_1 contract --alias my_contract
----
+
NOTE: The alias option allows you to interact with the contract later without using the address.

== Reading from a contract

Use `nile call` to read from a contract view function.

[,sh]
----
(env): nile call my_contract get_balance

0
----

== Writing to a contract

Use `nile send` to execute a transaction.

[,sh]
----
(env): nile send ACCOUNT_1 my_contract increase_balance 2
----